# Generated by Django 3.1.7 on 2021-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pgp_private',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
